config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :sessions, only: [:index, :show] do
    resources :playlists, only: [:index]
    namespace :my do
      resources :playlists, only: [:new, :create]
    end
  end
  namespace :my do
    resources :playlists, only: [:show, :update, :destroy]
  end
  resources :playlists, only: [:update]
  devise_scope :user do
    root to: 'static_pages#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :sessions, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true, length: { in: 50..260 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :song
  belongs_to :user
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  belongs_to :session
  has_many :songs
  validates :started_at, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :bar
  has_many :playlists
  validates :description, presence: true, length: { in: 50..260 }
  validates :category, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :playlist
  has_many :likes, dependent: :destroy
  validates :artist, presence: true
  validates :title, presence: true
  validates :duration, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  PASSWORD_FORMAT = /\A
  (?=.{8,})          # Must contain 8 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
/x
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :bars
  has_many :playlists
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :username, presence: true, format: { with: /\A[a-zA-Z0-9]+\Z/ }, uniqueness: true
  validates :password,
            presence: true,
            length: { in: Devise.password_length },
            format: { with: PASSWORD_FORMAT },
            confirmation: true,
            on: :create
  validates :password,
            allow_nil: true,
            length: { in: Devise.password_length },
            format: { with: PASSWORD_FORMAT },
            confirmation: true,
            on: :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/my/playlists_controller.rb
require 'json'
require 'open-uri'

class My::PlaylistsController < ApplicationController
  def show
    @playlist = Playlist.find(params[:id])
    @playlists = @playlist.session.playlists
  end

  def new
    if current_user.playlists.find_by(session_id: params[:session_id])
      @playlist = current_user.playlists.find_by(session_id: params[:session_id])
    else
      @playlist = Playlist.create(session_id: params[:session_id], user_id: current_user.id, started_at: Time.now)
    end
    if params[:search].present?
      songs_serialized = open("https://api.deezer.com/search?q=#{params[:search][:query]}").read
      @songs = JSON.parse(songs_serialized)
    else
      songs_serialized = open("https://api.deezer.com/chart/?limit=20").read
      @songs = JSON.parse(songs_serialized)
    end
    if current_user.playlists.find_by(session_id: params[:session_id]).present?
      @mysongs = current_user.playlists.find_by(session_id: params[:session_id]).songs
    end
  end

  def create
    if user_signed_in? && current_user.playlists.present?
      if current_user.playlists.where(session_id: params[:session_id]).present?
        @playlist = current_user.playlists.find_by(session_id: params[:session_id])
        if (@playlist.songs.count < 5)
          @song = Song.new(songs_params)
          @song.playlist_id = @playlist.id
          @song.save
          flash[:success] = "song added !"
        end
      else
        @playlist = Playlist.new(session_id: params[:session_id], user_id: current_user, started_at: Time.now)
        if @playlist.save
          @song = Song.new(songs_params)
          @song.playlist_id = @playlist.id
          @song.save
        end
      end
    end
    if @playlist.save
      respond_to do |format|
        format.html { redirect_to my_playlist_path(params[:session_id]) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'my/playlists/new' }
        format.js
      end
    end
  end

  def destroy
    @playlist = Playlist.find_by(session_id: params[:session_id], user_id: current_user.id)
    @songs = @playlist.songs
    @songs.each do |song|
      if song.artist == params[:song][:artist] && song.title == params[:song][:title]
        if song.destroy
          respond_to do |format|
            format.html { redirect_to new_session_my_playlist_path(session_id: params[:session_id]) }
            format.js
          end
        end
      end
    end
  end

  private

  def songs_params
    params.require(:song).permit(:artist, :album, :category, :duration, :title, :deezer_id, :composer, :photo_album, :photo_large, :photo_artist, :preview)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.where(session_id: params[:session_id])
  end

  def update
    if Like.where(user_id: current_user.id, song_id: params[:song]).empty?
      @like = Like.new(user_id: current_user.id, song_id: params[:song], status: params[:like])
      if @like.save
        respond_to do |format|
          format.html { redirect_to my_playlist_path }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'my/playlists/new' }
          format.js
        end
      end
    else
      @like = Like.where(user_id: current_user.id, song_id: params[:song])
      if @like.update(status: params[:like])
        respond_to do |format|
          format.html { redirect_to my_playlist_path }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'my/playlists/new' }
          format.js
        end
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:search].present?
      sql_query = "\
        sessions.category ILIKE :query \
        OR bars.address ILIKE :query \
        OR bars.name ILIKE :query \
      "
      @sessions = Session.joins(:bar).where(sql_query, query: "%#{params[:search][:query]}%")
      @sessions.each do |session|
        session.bar.geocode
      end
    else
      @sessions = Session.all
      @sessions.each do |session|
        session.bar.geocode
      end
    end

    @markers = @sessions.map do |session|
      {
        lat: session.bar.latitude,
        lng: session.bar.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { session: session }),
        image_url: helpers.asset_url('https://www.google.fr/imgres?imgurl=https%3A%2F%2Fshannon-pub.fr%2Fwp-content%2Fuploads%2F2018%2F04%2FShannon-17.jpg&imgrefurl=https%3A%2F%2Fshannon-pub.fr%2F&docid=ayLTPYvKrwud3M&tbnid=R2PoFeODeo83eM%3A&vet=10ahUKEwjy54jVo4jmAhUQzhoKHQJYBHAQMwhgKBUwFQ..i&w=1000&h=667&bih=814&biw=1440&q=photo%20bar%20dansant&ved=0ahUKEwjy54jVo4jmAhUQzhoKHQJYBHAQMwhgKBUwFQ&iact=mrc&uact=8')      }
    end
  end

  def show
    @session = Session.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <title><%= DEFAULT_META["meta_title"] %></title>
    <meta name="description" content="<%= DEFAULT_META['meta_description'] %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= DEFAULT_META['meta_title'] %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= DEFAULT_META['meta_image'] %>" />
    <meta property="og:description" content="<%= DEFAULT_META['meta_description'] %>" />
    <meta property="og:site_name" content="<%= DEFAULT_META['meta_title'] %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= DEFAULT_META['meta_title'] %>">
    <meta name="twitter:description" content="<%= DEFAULT_META['meta_description'] %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= DEFAULT_META['meta_image'] %>">
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/my/playlists/new.html.erb
<!-- <script>   let playlists = document.querySelectorAll(".children") </script> -->
<div class="d-flex flex-column">
  <div class="search_playlist" id="navbar_playlist">
    <div class="nav_search_bar">
      <%= link_to session_playlists_path(@playlist.session.id) do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
      <h3>Sélection <%= @playlist.session.bar.name %></h3>
      <i class="fas fa-bars" style="font-size: 35px;"></i>
    </div>
    <%= simple_form_for :song, url: new_session_my_playlist_path(@playlist.session_id), method: :get do %>
      <div id="accordion_search_bar_container">
        <input type="search"
          name="search[query]"
          id="accordion_search_bar"
          placeholder="Themes, artistes, titres..."/>
      </div>
    <% end %>
  </div>

  <div id="myplaylist">
    <% if !@mysongs.nil? %>
      <div class="hearder-playlist-card">
        <div class="d-flex justify-content-center pt-3">
            <h3>Ma Playlist</h3>
        </div>
      </div>
      <div class='playlist container-playlist-card' id='first-card'>
        <% @mysongs.each do |song| %>
          <%= link_to my_playlist_path(@playlist.id, song: {title: song.title,  artist: song.artist, album: song.album, duration: song.duration, deezer_id: song.deezer_id, photo_album: song.photo_album, photo_album: song.photo_artist, photo_large: song.photo_large,  preview: song.preview }, session_id: params[:session_id]), method: :delete, remote: true do  %>
            <div class="playlist-list d-flex justify-content-between children-destroy">
              <div class="d-flex text-left align-items-center">
                <span class="mr-3 mt-3"> •</span>
                <%= image_tag song.photo_album, alt: "alttext", width:114, height:114 %>
                <span class="ml-3 ellipsis">
                  <h3>
                    <%= song.artist %>
                  </h3>
                  <h4>
                    <%= song.album %>
                  </h4>
                  <h5>
                    <%= song.title %>
                  </h5>
                </span>
              </div>
              <div class="d-flex align-items-center pr-4">
                <span class="text-center"><i class="fas fa-check icon-medium"></i></span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <div class="hearder-playlist-card">
        <div class="user-info d-flex justify-content-center pt-3">
            <h3>MA SELECTION</h3>
        </div>
      </div>
      <div class='playlist container-playlist-card' id='first-card'>
      </div>
    <% end %>
  </div>

  <div class="topcard">
    <div class="playlist container-playlist-card" id="top-playlist" >
      <% @songs_var = @songs['data'] == nil ? @songs['tracks']['data'] : @songs['data'] %>
      <% i = 1 %>
      <% @songs_var.map do |song| %>
        <% if (i==1) && !(@mysongs.map { |s| s.title }.include?(song["title"])) && !(@mysongs.map { |s| s.artist }.include?(song["artist"]["name"])) %>
          <%= link_to session_my_playlists_path(params[:session_id], song: {title: song["title"],  artist: song["artist"]["name"], album: song["album"]["title"], duration: song["duration"], deezer_id: song["id"], photo_album: song["album"]["cover_small"], photo_album: song["artist"]["picture_small"], photo_large: song["album"]["cover_big"],  preview: song["preview"] }), method: :post, remote: true do  %>
            <div class="playlist-list-first d-flex justify-content-between children">
              <div class="d-flex text-left align-items-center">
                <span class="mr-3 mt-3"> •</span>
                <%= image_tag song["album"]["cover_small"], alt: "alttext", width:114, height:114 %>
                <span class="ml-3 ellipsis">
                  <h3>
                    <%= song["artist"]["name"] %>
                  </h3>
                  <h4>
                    <%= song["album"]["title"] %>
                  </h4>
                  <h5>
                    <%= song["title"] %>
                  </h5>
                </span>
              </div>
              <div class="d-flex align-items-center pr-4">
                <span class="text-center"><i class="fas fa-plus icon-medium"></i></span>
              </div>
            </div>
          <% end %>
          <% i += 1 %>
        <% elsif !@mysongs.map { |s| s.title }.include?(song["title"]) && !@mysongs.map { |s| s.artist }.include?(song["artist"]["name"]) %>
          <%= link_to session_my_playlists_path(params[:session_id], song: {title: song["title"],  artist: song["artist"]["name"], album: song["album"]["title"], duration: song["duration"], deezer_id: song["id"], photo_album: song["album"]["cover_small"], photo_album: song["artist"]["picture_small"], photo_large: song["album"]["cover_big"],  preview: song["preview"] }), method: :post, remote: true do  %>
            <div class="playlist-list d-flex justify-content-between children">
              <div class="d-flex text-left align-items-center">
                <span class="mr-3 mt-3"> •</span>
                <%= image_tag song["album"]["cover_small"], alt: "alttext", width:114, height:114 %>
                <span class="ml-3 ellipsis">
                  <h3>
                    <%= song["artist"]["name"] %>
                  </h3>
                  <h4>
                    <%= song["album"]["title"] %>
                  </h4>
                  <h5>
                    <%= song["title"] %>
                  </h5>
                </span>
              </div>
              <div class="d-flex align-items-center pr-4">
                <span class="text-center"><i class="fas fa-plus icon-medium"></i></span>
              </div>
            </div>
          <% end %>
          <% i += 1 %>
        <% end %>
      <% end %>
    </div>
  <div class="d-flex justify-content-center mb-5">
    <%= link_to "valider", my_playlist_path(current_user.playlists.find_by(session_id: params[:session_id]).id), class: "button button-1"  %>
  </div>

app/views/my/playlists/new.js.erb
const song = () => {
  if (document.getElementById("top-playlist")) {
    const playlists = document.getElementById("top-playlist").children
    for (let i=0; i<playlists.length - 1; i+=1) {
      playlists[i].addEventListener("click", (e) => {
        playlists[i].children["1"].children["0"].children["0"].classList.toggle("fa-plus");
        playlists[i].children["1"].children["0"].children["0"].classList.toggle("fa-check");
        console.dir(playlists[i].children["1"].children["0"].children["0"].classList);

        const myPlaylist = document.getElementById("first-card");
        console.log(myPlaylist)
        console.dir(document.getElementById("first-card"));
        if (document.getElementById("first-card").children.length === 0){
          myPlaylist.style.display = "";
          myPlaylist.insertAdjacentHTML("beforeend", "<div class='playlist-list-first d-flex justify-content-between' data-song-title='<%= song['title'] %>' data-song-artist='<%= song['artist']['name'] %>' data-song-album='<%= song['album']['title'] %>' data-song-duration='<%= song['duration'] %>' data-song-deezer-id='<%= song['id'] %>' data-song-photo-album='<%= song['album']['cover_small'] %>' data-song-photo-album='<%= song['artist']['picture_small'] %>' data-remote='true' ><div class='d-flex text-left'> \
            <span class='mr-3 mt-3'><%= i %> •</span><%= image_tag song['album']['cover_small'], alt: 'alttext' %> \
            <span class='ml-3'><h5><%= song['artist']['name'] %></h5> \
            <p><%= song['title'] %></p></span></div> \
            <div class='d-flex flex-column'><span class='text-center'><i class='fas fa-plus'></i></span></div>")
        }else if (playlists[i].children["1"].children["0"].children["0"].classList["1"] === "fa-check") {
          myPlaylist.insertAdjacentHTML("beforeend", "<div class='playlist-list d-flex justify-content-between' data-song-title='<%= song['title'] %>' data-song-artist='<%= song['artist']['name'] %>' data-song-album='<%= song['album']['title'] %>' data-song-duration='<%= song['duration'] %>' data-song-deezer-id='<%= song['id'] %>' data-song-photo-album='<%= song['album']['cover_small'] %>' data-song-photo-album='<%= song['artist']['picture_small'] %>' data-remote='true' ><div class='d-flex text-left'> \
              <span class='mr-3 mt-3'><%= i %> •</span><%= image_tag song['album']['cover_small'], alt: 'alttext' %> \
              <span class='ml-3'><h5><%= song['artist']['name'] %></h5> \
              <p><%= song['title'] %></p></span></div> \
              <div class='d-flex flex-column'><span class='text-center'><i class='fas fa-plus'></i></span></div>")
        } else {


        }
     });
    };
  }
}

song();

app/views/my/playlists/show.html.erb
<div class="container-playlist-card">
  <div class="header-playlist">
    <div class="nav_search_bar d-flex justify-content-between">
      <%= link_to session_playlists_path(@playlist.session_id) do  %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
      <i class="fas fa-bars" style="font-size: 35px;"></i>
    </div>
    <div class="d-flex justify-content-between align-items-center p-3">

      <div class="text-center playlist-titles">
        <h2 class="mt-4"><%= @playlists.first.songs[0].artist %></h2>
        <h4><%= @playlists.first.songs[0].title %></h4>
        <h5><%= @playlists.first.songs[0].album %></h5>

      </div>
      <div>
        <%= image_tag @playlists.first.songs[0].photo_large, width: 250, height: 250 %>
      </div>
      <div class="d-flex align-items-center justify-content-around w-25">
         <% if @playlist.session.category == "Latino"%>
          <div  class="avatar-thema-med moncercle-orange"></div>
          <% elsif @playlist.session.category == "pop"%>
          <div  class="avatar-thema-med moncercle-noir"></div>
          <% elsif @playlist.session.category == "RnB"%>
          <div  class="avatar-thema-med moncercle-cyan"></div>
          <% elsif @playlist.session.category == "Electro"%>
          <div  class="avatar-thema-med moncercle-vert"></div>
          <% elsif @playlist.session.category == "Année 80"%>
          <div  class="avatar-thema-med moncercle-marron"></div>
          <% elsif @playlist.session.category == "rap"%>
          <div  class="avatar-thema-med moncercle-magenta"></div>
          <% elsif @playlist.session.category == "Jazz"%>
          <div  class="avatar-thema-med moncercle-blue"></div>
          <% elsif @playlist.session.category == "Rock"%>
          <div  class="avatar-thema-med moncercle-vert"></div>
          <% else %>
          <div></div>
          <% end %>

        <div class="text-center align-items-center">
          <% if !@playlists.first.songs[0].likes.empty? && @playlists.first.songs[0].likes.find_by(user_id: current_user.id, song_id: @playlists.first.songs[0].id) && @playlists.first.songs[0].likes.find_by(user_id: current_user.id, song_id: @playlists.first.songs[0].id).status == true %>
            <%= link_to playlist_path(@playlists.first.id, like: false, song: @playlists.first.songs[0].id), class: "text-center", method: :patch, remote: true do %>
              <i class="fas fa-heart icon-large" style="color: #BA1B1D;"></i>
            <% end %>
          <% else %>
            <%= link_to playlist_path(@playlists.first.id, like: true, song: @playlists.first.songs[0].id), class: "text-center", method: :patch, remote: true do %>
              <i class="far fa-heart icon-large" style="color: white"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
     <div class="w-100">
      <svg viewBox="0 0 100 5" xmlns="http://www.w3.org/2000/svg" id="top-waves">
        <% i = 0 %>
        <% 320.times do %>
          <rect x=<%= i %> y="0" width="0.1" height=<%= (1..5).to_a.sample %> rx="4" ry="4" fill="white" class=<%="wave-#{(1..5).to_a.sample}"%>  transform="translate(95.7,05) rotate(180)"></rect>
          <% i += 0.3 %>
        <% end %>
      </svg>
      <hr color="white" width="747">
      <svg viewBox="0 0 100 5" xmlns="http://www.w3.org/2000/svg" id="bottom-waves">
        <% i = 0 %>
        <% 320.times do %>
          <rect x=<%= i %> y="0" width="0.1" height=<%= (1..5).to_a.sample %> rx="4" ry="4" fill="white" class=<%= "wave-#{(1..5).to_a.sample}" %>></rect>
          <% i += 0.3 %>
        <% end %>
      </svg>
    </div>
  </div>
  <div class="hearder-playlist-card">
    <div class="user-info d-flex align-items-center justify-content-between">
      <div class="d-flex align-items-center pt-3">
        <img src=<%= current_user.photo %> alt= playlist.user.username class="avatar-playlist-card">
        <h4 class="ml-3"><%= @playlist.user.username %></h4>
      </div>
      <div class="text-right pt-4">
        <p>
          <% sum = 0 %>
          <% @playlist.songs.each do |song| %>
            <% sum += song.duration %>
          <% end %>
          <%= Time.at(sum).utc.strftime("%M:%S") %>
        </p>
      </div>
    </div>
  </div>
  <div class="playlist">
    <% sum = 0 %>
    <% i = 1 %>
    <% @playlist.songs.each do |song| %>
      <% sum += song.duration %>
      <% if i==1 %>
        <div class="playlist-list-first d-flex justify-content-between" data-song-id="<%= song.id %>" data-song-title="<%= song.title %>" data-song-artist="<%= song.artist %>" data-song-album="<%= song.album %>" data-song-category="<%= song.category %>" data-song-duration="<%= song.duration %>" data-song-deezer-id="<%= song.deezer_id %>" data-song-composer="<%= song.composer %>" data-remote="true">
          <div class="d-flex font-height-shrink align-items-center">
            <span class="mr-3 mt-3"> •</span>
            <%= image_tag song.photo_album, alt: song.album, width:114, height:114 %>
            <span class="ml-3 black-color">
              <h3>
                <%= song.artist %>
              </h3>
              <h4>
                <%= song.album %>
              </h4>
              <h5 class="black-color">
                <%= song.title %>
              </h5>
            </span>
          </div>
          <div class="duration-heart d-flex flex-column justify-content-center pr-4">
            <span class="my-1">-<%= Time.at(song.duration).utc.strftime("%M:%S")  %></span>
              <% if !song.likes.empty? && song.likes.find_by(user_id: current_user.id, song_id: song.id) && song.likes.find_by(user_id: current_user.id, song_id: song.id).status == true %>
                <%= link_to playlist_path(@playlist.id, like: false, song: song.id), class: "text-center", method: :patch, remote: true do %>
                  <i class="fas fa-heart" style="color: rgb(186, 27, 29);"></i>
                <% end %>
              <% else %>
                <%= link_to playlist_path(@playlist.id, like: true, song: song.id), class: "text-center", method: :patch, remote: true do %>
                  <i class="far fa-heart" style="color: #262525;"></i>
                <% end %>
              <% end %>
          </div>
        </div>
        <% i += 1 %>
      <% else %>
        <div class="playlist-list d-flex justify-content-between" data-song-id="<%= song.id %>" data-song-title="<%= song.title %>" data-song-artist="<%= song.artist %>" data-song-album="<%= song.album %>" data-song-category="<%= song.category %>" data-song-duration="<%= song.duration %>" data-song-deezer-id="<%= song.deezer_id %>" data-song-composer="<%= song.composer %>" data-remote="true">
          <div class="d-flex font-height-shrink align-items-center">
            <span class="mr-3 mt-3"> •</span>
            <%= image_tag song.photo_album, alt: song.album, width:114, height:114 %>
            <span class="ml-3 black-color">
              <h3>
                <%= song.artist %>
              </h3>
              <h4>
                <%= song.album %>
              </h4>
              <h5 class="black-color">
                <%= song.title %>
              </h5>
            </span>
          </div>
          <div class="duration-heart d-flex flex-column justify-content-center pr-4">
            <span class="my-1">-<%= Time.at(song.duration).utc.strftime("%M:%S")  %></span>
              <% if !song.likes.empty? && song.likes.find_by(user_id: current_user.id, song_id: song.id) && song.likes.find_by(user_id: current_user.id, song_id: song.id).status == true %>
                <%= link_to playlist_path(@playlist.id, like: false, song: song.id), class: "text-center", method: :patch, remote: true do %>
                  <i class="fas fa-heart" style="color: rgb(186, 27, 29);"></i>
                <% end %>
              <% else %>
                <%= link_to playlist_path(@playlist.id, like: true, song: song.id), class: "text-center", method: :patch, remote: true do %>
                  <i class="far fa-heart" style="color: #262525;"></i>
                <% end %>
              <% end %>
          </div>
        </div>
        <% i += 1 %>
      <% end %>
    <% end %>
  </div>
  <% if @playlist.session.bar.name == "Le Wagon" %>
    <audio src=<%= @playlist.songs.first.preview %> autoplay></audio>
  <% end %>
  <div class="d-flex justify-content-center my-2">
    <div class="wrap">
      <a href="#openModal01" class="button button-1">Valider</a> <br />
      <div id="openModal01" class="modalDialog">
        <div class="popWrap">
          <h2 class="popTit">Félicitation ! </h2>
          <div class="popCont">
            <p>Vous êtes à la <%= @playlist.session.playlists.count %><% if @playlist.session.playlists.count == 1 %>ère position<% else %>ème position<% end %></p>
          </div>
          <div class="d-flex justify-content-center">
            <%= link_to "valider", session_playlists_path(@playlist.session_id), class: "button button-1"  %>
          </div>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/pages/home.html.erb
  <div class="home-page container-fluid d-flex justify-content-center align-center">
    <div class="d-flex flex-column text-center justify-content-center">
      <h1 id="title-home">JUXBAR</h1>
      <div hidden><%= link_to "Enter", sessions_path, class: "button text-center", id: "btn-home" %></div>
    </div>
  </div>

app/views/playlists/update.js.erb
const hearts = document.querySelectorAll(".fa-heart");

hearts.forEach((heart) => {
  heart.addEventListener("click", (e) => {
    if (e.target.id !== "heart") {
      e.target.classList.toggle("fas");
      e.target.classList.toggle("far");
      e.target.style.color = e.target.style.color === 'rgb(186, 27, 29)' ? 'rgb(38, 37, 37)' : 'rgb(186, 27, 29)';
    }
  });
});